apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: fib-node
spec:
  componentName: fib-node
  application: graphtuitous
  source:
    git:
      url: https://github.com/jduimovich/graphtuitous
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e/main/devfiles/fib-node/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/fib-node
  
