apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: frontend
spec:
  componentName: frontend
  application: graphtuitous
  source:
    git:
      url: https://github.com/jduimovich/graphtuitous
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e/main/devfiles/frontend/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/frontend
  
