apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: frontend
spec:
  componentName: frontend
  application: graphtuitous
  containerImage: quay.io/jduimovich0/frontend
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  source:
    git:
      url: https://github.com/jduimovich/graphtuitous
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/graphtuitous/devfiles/frontend/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/frontend
  
