apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: haproxy
spec:
  componentName: haproxy
  application: graphtuitous 
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
  source:
    git:
      url: https://github.com/jduimovich/graphtuitous
      context: haproxy 