apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: service-registry
spec:
  description: "service-registry built in App Studio"
  displayName: "service-registry build-only example"