apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: actions-to-appstudio
spec:
  componentName: actions-to-appstudio
  application: actions-to-appstudio 
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 512Mi 
