apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name:  ux-github-actions
spec:
  componentName:  ux-github-actions
  application:  ux-github-actions
  containerImage: ghcr.io/jduimovich/ux-github-actions:latest
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
  source:
    git:
      url: https://github.com/jduimovich/actions-to-appstudio
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/ux-github-actions/devfiles/devfile.yaml
  build:
    containerImage: ghcr.io/jduimovich/ux-github-actions:latest
