apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: actions-to-appstudio
spec:
  componentName: actions-to-appstudio
  application: use-github-as-ci
  containerImage: ghcr.io/jduimovich/actions-to-appstudio:latest
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
  build:
    containerImage: ghcr.io/jduimovich/actions-to-appstudio:latest
