apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: managed-gitops
spec:
  componentName: managed-gitops
  application: dogfood-builds
  containerImage: quay.io/jduimovich0/managed-gitops
  skipGitOpsResourceGeneration: true
  source:
    git:
      url: https://github.com/redhat-appstudio/managed-gitops
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/dogfood-builds/devfiles/managed-gitops/devfile.yaml
 