apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: dc-metro-map 
spec:
  description: "dc-metro-map built in App Studio"
  # displayName: "DC Metro Map Example"
  displayName: "dc-metro-map"