apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: devfile-sample-code-with-quarkus
spec:
  componentName: devfile-sample-code-with-quarkus
  application: nyc-transit
  containerImage: quay.io/jduimovich0/devfile-sample-code-with-quarkus
  source:
    git:
      url: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
  build:
    containerImage: quay.io/jduimovich0/devfile-sample-code-with-quarkus
  
