apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: billing-service
spec:
  componentName: billing-service
  application: nyc-transit
  containerImage: quay.io/jduimovich0/devfile-sample-code-with-quarkus
  targetPort: 8081
  source:
    git:
      url: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
  build:
    containerImage: quay.io/jduimovich0/devfile-sample-code-with-quarkus
  
