apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: auto-rebuild
spec:
  # the name auto-build is chosen not to conflict with the binary only install "rebuilder"
  componentName: auto-rebuild
  application: auto-rebuild 
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  source:
    git:
      url: https://github.com/jduimovich/rebuilder
 