apiVersion: route.openshift.io/v1
kind: Route
metadata:  
  name: map-service 
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: map-service 
    weight: 100 
