apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: single-nodejs-app
spec:
  componentName: single-nodejs-app
  application: single-nodejs-app
  containerImage: quay.io/jduimovich0/single-nodejs-app 
  targetPort: 8080
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
  source:
    git:
      url: https://github.com/jduimovich/single-nodejs-app
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/single-nodejs-app/devfiles/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/single-nodejs-app
  
