apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: mongodb
spec:
  componentName: mongodb
  application: mongo-pacman
  containerImage: quay.io/jduimovich0/mongodb
  targetPort: 27017
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
  source:
    git:
      url:   https://github.com/jduimovich/mongodb
      revision: updates


