apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: kcp
spec:
  componentName: kcp
  application: kcp
  containerImage: quay.io/jduimovich0/kcp
  source:
    git:
      url: https://github.com/kcp-dev/kcp
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/kcp/devfiles/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/kcp

