apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: %s
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: %s
    server: 'https://kubernetes.default.svc'
  source:
    path: %s
    repoURL: %s
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
