apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: sna
spec:
  componentName: sna
  application: sna
  containerImage: quay.io/redhat-appstudio/user-workload:sna
  targetPort: 8080
  source:
    git:
      url: https://github.com/jduimovich/single-nodejs-app
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/sna/devfiles/devfile.yaml
  build:
    containerImage: quay.io/redhat-appstudio/user-workload:sna
  
