apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: devfile-sample-java-springboot-basic
spec:
  description: "The devfile sample for springboot"
  # displayName: "Devfile sample for springboot"
  displayName: "devfile-sample-java-springboot-basic"