apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: single-container-app
spec:
  componentName: single-container-app
  application: single-container-app
  containerImage: quay.io/jduimovich0/single-container-app
  source:
    git:
      url: https://github.com/jduimovich/single-container-app
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/single-container-app/devfiles/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/single-container-app
  
