apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: service-registry
spec:
  componentName: service-registry
  application: service-registry
  containerImage: quay.io/jduimovich0/service-registry
  source:
    git:
      url: https://github.com/Apicurio/apicurio-registry
      revision: main
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/service-registry/devfiles/devfile.yaml
 